on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to'
        required: true
        default: 'stage'
        type: choice
        options:
        - stage
        - production

jobs:
  deploy-to-stage:
    if: ${{ inputs.environment }} == 'stage'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
