on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to'
        required: true
        default: 'stage'
        type: choice
        options:
        - stage
        - production

jobs:
  deploy-to-stage:
    if: ${{ inputs.environment }} == 'stage'
    runs-on: ubuntu-latest
    environment: githubactions
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_STAGE }}
        username: ${{ secrets.USERNAME_STAGE }}
        password: ${{ secrets.PASSWORD_STAGE }}
        script: whoami
