name: executing remote ssh commands using password
on: [push]
uses: appleboy/ssh-action@v0.1.7
with:
  host: ${{ secrets.HOST }}
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}
  port: ${{ secrets.PORT }}
  script: whoami
